import { MigrationInterface, QueryRunner } from "typeorm";

export class newDB1680636852470 implements MigrationInterface {
    name = 'newDB1680636852470'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`roles\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` int NOT NULL AUTO_INCREMENT, \`username\` varchar(255) NOT NULL, \`hash_password\` varchar(255) NOT NULL, \`roleId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`images\` (\`id\` int NOT NULL AUTO_INCREMENT, \`key\` varchar(255) NOT NULL, \`location\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`specie\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`classification\` varchar(255) NOT NULL, \`designation\` varchar(255) NOT NULL, \`average_height\` int NOT NULL, \`skin_colors\` varchar(255) NOT NULL, \`hair_colors\` varchar(255) NOT NULL, \`eye_colors\` varchar(255) NOT NULL, \`average_lifespan\` int NOT NULL, \`language\` varchar(255) NOT NULL, \`created\` varchar(255) NOT NULL, \`edited\` varchar(255) NOT NULL, \`homeworldId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`planet\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`rotation_period\` int NOT NULL, \`orbital_period\` int NOT NULL, \`diameter\` int NOT NULL, \`climate\` varchar(255) NOT NULL, \`gravity\` varchar(255) NOT NULL, \`terrain\` varchar(255) NOT NULL, \`surface_water\` int NOT NULL, \`population\` int NOT NULL, \`created\` varchar(255) NOT NULL, \`edited\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`starship\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`model\` varchar(255) NOT NULL, \`manufacturer\` varchar(255) NOT NULL, \`cost_in_credits\` int NOT NULL, \`length\` int NOT NULL, \`max_atmosphering_speed\` int NOT NULL, \`crew\` int NOT NULL, \`passengers\` int NOT NULL, \`cargo_capacity\` int NOT NULL, \`consumables\` varchar(255) NOT NULL, \`hyperdrive_rating\` int NOT NULL, \`MGLT\` int NOT NULL, \`starship_class\` varchar(255) NOT NULL, \`created\` varchar(255) NOT NULL, \`edited\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`vehicle\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`model\` varchar(255) NOT NULL, \`manufacturer\` varchar(255) NOT NULL, \`cost_in_credits\` varchar(255) NOT NULL, \`length\` int NOT NULL, \`max_atmosphering_speed\` int NOT NULL, \`crew\` int NOT NULL, \`passengers\` int NOT NULL, \`cargo_capacity\` int NOT NULL, \`consumables\` varchar(255) NOT NULL, \`vehicle_class\` varchar(255) NOT NULL, \`created\` varchar(255) NOT NULL, \`edited\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`film\` (\`id\` int NOT NULL AUTO_INCREMENT, \`title\` varchar(255) NOT NULL, \`episode_id\` int NOT NULL, \`opening_crawl\` varchar(255) NOT NULL, \`director\` varchar(255) NOT NULL, \`producer\` varchar(255) NOT NULL, \`release_date\` varchar(255) NOT NULL, \`created\` varchar(255) NOT NULL, \`edited\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`person\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`height\` int NOT NULL, \`mass\` int NOT NULL, \`hair_color\` varchar(255) NOT NULL, \`skin_color\` varchar(255) NOT NULL, \`eye_color\` varchar(255) NOT NULL, \`birth_year\` varchar(255) NOT NULL, \`gender\` varchar(255) NOT NULL, \`created\` varchar(255) NOT NULL, \`edited\` varchar(255) NOT NULL, \`homeworldId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`specie_images_images\` (\`specieId\` int NOT NULL, \`imagesId\` int NOT NULL, INDEX \`IDX_42f307c19ca832703852189497\` (\`specieId\`), INDEX \`IDX_2ad1e7a7930c3ccaf75d4a7f05\` (\`imagesId\`), PRIMARY KEY (\`specieId\`, \`imagesId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`planet_images_images\` (\`planetId\` int NOT NULL, \`imagesId\` int NOT NULL, INDEX \`IDX_1de22794654cb72e7538b865cd\` (\`planetId\`), INDEX \`IDX_2ab67e264e6edbb7427f6fea3c\` (\`imagesId\`), PRIMARY KEY (\`planetId\`, \`imagesId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`starship_images_images\` (\`starshipId\` int NOT NULL, \`imagesId\` int NOT NULL, INDEX \`IDX_7aabd339010e33f15747fba209\` (\`starshipId\`), INDEX \`IDX_f522274334f590ce009b5e4282\` (\`imagesId\`), PRIMARY KEY (\`starshipId\`, \`imagesId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`vehicle_images_images\` (\`vehicleId\` int NOT NULL, \`imagesId\` int NOT NULL, INDEX \`IDX_7a473001e3be0882cc92ff11d8\` (\`vehicleId\`), INDEX \`IDX_75dfb54dd3747d2828cff22efe\` (\`imagesId\`), PRIMARY KEY (\`vehicleId\`, \`imagesId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`film_characters_person\` (\`filmId\` int NOT NULL, \`personId\` int NOT NULL, INDEX \`IDX_7c9df9a723ecdbadcfe8362646\` (\`filmId\`), INDEX \`IDX_76a39805866b99358326c6153a\` (\`personId\`), PRIMARY KEY (\`filmId\`, \`personId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`film_planets_planet\` (\`filmId\` int NOT NULL, \`planetId\` int NOT NULL, INDEX \`IDX_9e9d858b064b7d0fa02a9764e1\` (\`filmId\`), INDEX \`IDX_6821d91826ca31cc4e4588b535\` (\`planetId\`), PRIMARY KEY (\`filmId\`, \`planetId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`film_starships_starship\` (\`filmId\` int NOT NULL, \`starshipId\` int NOT NULL, INDEX \`IDX_ed79253745f81534b737ce768c\` (\`filmId\`), INDEX \`IDX_21297c5d74a841542bcb7fe063\` (\`starshipId\`), PRIMARY KEY (\`filmId\`, \`starshipId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`film_vehicles_vehicle\` (\`filmId\` int NOT NULL, \`vehicleId\` int NOT NULL, INDEX \`IDX_af46f6d0bef8eba92546a8c537\` (\`filmId\`), INDEX \`IDX_8be4e7e1014359bb4715338cf2\` (\`vehicleId\`), PRIMARY KEY (\`filmId\`, \`vehicleId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`film_species_specie\` (\`filmId\` int NOT NULL, \`specieId\` int NOT NULL, INDEX \`IDX_57e6df74dce55bd710f01c44bb\` (\`filmId\`), INDEX \`IDX_5a19d397f578506a444ad76cfa\` (\`specieId\`), PRIMARY KEY (\`filmId\`, \`specieId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`film_images_images\` (\`filmId\` int NOT NULL, \`imagesId\` int NOT NULL, INDEX \`IDX_020d6919690a7a20524282e6c9\` (\`filmId\`), INDEX \`IDX_89bc78f7ac425ace2f1ac3765f\` (\`imagesId\`), PRIMARY KEY (\`filmId\`, \`imagesId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`person_species_specie\` (\`personId\` int NOT NULL, \`specieId\` int NOT NULL, INDEX \`IDX_10f5e82ddc0e1f67f779f37c21\` (\`personId\`), INDEX \`IDX_768ccc6a23ed03f3e4fc27cd83\` (\`specieId\`), PRIMARY KEY (\`personId\`, \`specieId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`person_vehicles_vehicle\` (\`personId\` int NOT NULL, \`vehicleId\` int NOT NULL, INDEX \`IDX_93eb9aed40f347d6d9eb37af39\` (\`personId\`), INDEX \`IDX_dcca73435d3a911aec3a8c6a8e\` (\`vehicleId\`), PRIMARY KEY (\`personId\`, \`vehicleId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`person_starships_starship\` (\`personId\` int NOT NULL, \`starshipId\` int NOT NULL, INDEX \`IDX_5b4b4623267b28750ae11a5309\` (\`personId\`), INDEX \`IDX_18aaf7b5a5268c1d99b1385adf\` (\`starshipId\`), PRIMARY KEY (\`personId\`, \`starshipId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`person_images_images\` (\`personId\` int NOT NULL, \`imagesId\` int NOT NULL, INDEX \`IDX_4c09184fd2f6dba71e77bb8fde\` (\`personId\`), INDEX \`IDX_4592909e9fff3e1deaf5f4fbf1\` (\`imagesId\`), PRIMARY KEY (\`personId\`, \`imagesId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_368e146b785b574f42ae9e53d5e\` FOREIGN KEY (\`roleId\`) REFERENCES \`roles\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`specie\` ADD CONSTRAINT \`FK_55bd54b68d6b9484ec932556182\` FOREIGN KEY (\`homeworldId\`) REFERENCES \`planet\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`person\` ADD CONSTRAINT \`FK_997edaa4b7b556c0d557cc6e1bb\` FOREIGN KEY (\`homeworldId\`) REFERENCES \`planet\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`specie_images_images\` ADD CONSTRAINT \`FK_42f307c19ca832703852189497a\` FOREIGN KEY (\`specieId\`) REFERENCES \`specie\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`specie_images_images\` ADD CONSTRAINT \`FK_2ad1e7a7930c3ccaf75d4a7f050\` FOREIGN KEY (\`imagesId\`) REFERENCES \`images\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`planet_images_images\` ADD CONSTRAINT \`FK_1de22794654cb72e7538b865cd1\` FOREIGN KEY (\`planetId\`) REFERENCES \`planet\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`planet_images_images\` ADD CONSTRAINT \`FK_2ab67e264e6edbb7427f6fea3c8\` FOREIGN KEY (\`imagesId\`) REFERENCES \`images\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`starship_images_images\` ADD CONSTRAINT \`FK_7aabd339010e33f15747fba209b\` FOREIGN KEY (\`starshipId\`) REFERENCES \`starship\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`starship_images_images\` ADD CONSTRAINT \`FK_f522274334f590ce009b5e4282e\` FOREIGN KEY (\`imagesId\`) REFERENCES \`images\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`vehicle_images_images\` ADD CONSTRAINT \`FK_7a473001e3be0882cc92ff11d86\` FOREIGN KEY (\`vehicleId\`) REFERENCES \`vehicle\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`vehicle_images_images\` ADD CONSTRAINT \`FK_75dfb54dd3747d2828cff22efef\` FOREIGN KEY (\`imagesId\`) REFERENCES \`images\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`film_characters_person\` ADD CONSTRAINT \`FK_7c9df9a723ecdbadcfe83626467\` FOREIGN KEY (\`filmId\`) REFERENCES \`film\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`film_characters_person\` ADD CONSTRAINT \`FK_76a39805866b99358326c6153a0\` FOREIGN KEY (\`personId\`) REFERENCES \`person\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`film_planets_planet\` ADD CONSTRAINT \`FK_9e9d858b064b7d0fa02a9764e18\` FOREIGN KEY (\`filmId\`) REFERENCES \`film\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`film_planets_planet\` ADD CONSTRAINT \`FK_6821d91826ca31cc4e4588b5355\` FOREIGN KEY (\`planetId\`) REFERENCES \`planet\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`film_starships_starship\` ADD CONSTRAINT \`FK_ed79253745f81534b737ce768c1\` FOREIGN KEY (\`filmId\`) REFERENCES \`film\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`film_starships_starship\` ADD CONSTRAINT \`FK_21297c5d74a841542bcb7fe063a\` FOREIGN KEY (\`starshipId\`) REFERENCES \`starship\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`film_vehicles_vehicle\` ADD CONSTRAINT \`FK_af46f6d0bef8eba92546a8c5375\` FOREIGN KEY (\`filmId\`) REFERENCES \`film\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`film_vehicles_vehicle\` ADD CONSTRAINT \`FK_8be4e7e1014359bb4715338cf20\` FOREIGN KEY (\`vehicleId\`) REFERENCES \`vehicle\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`film_species_specie\` ADD CONSTRAINT \`FK_57e6df74dce55bd710f01c44bb8\` FOREIGN KEY (\`filmId\`) REFERENCES \`film\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`film_species_specie\` ADD CONSTRAINT \`FK_5a19d397f578506a444ad76cfac\` FOREIGN KEY (\`specieId\`) REFERENCES \`specie\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`film_images_images\` ADD CONSTRAINT \`FK_020d6919690a7a20524282e6c9d\` FOREIGN KEY (\`filmId\`) REFERENCES \`film\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`film_images_images\` ADD CONSTRAINT \`FK_89bc78f7ac425ace2f1ac3765f2\` FOREIGN KEY (\`imagesId\`) REFERENCES \`images\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`person_species_specie\` ADD CONSTRAINT \`FK_10f5e82ddc0e1f67f779f37c21e\` FOREIGN KEY (\`personId\`) REFERENCES \`person\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`person_species_specie\` ADD CONSTRAINT \`FK_768ccc6a23ed03f3e4fc27cd839\` FOREIGN KEY (\`specieId\`) REFERENCES \`specie\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`person_vehicles_vehicle\` ADD CONSTRAINT \`FK_93eb9aed40f347d6d9eb37af39c\` FOREIGN KEY (\`personId\`) REFERENCES \`person\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`person_vehicles_vehicle\` ADD CONSTRAINT \`FK_dcca73435d3a911aec3a8c6a8eb\` FOREIGN KEY (\`vehicleId\`) REFERENCES \`vehicle\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`person_starships_starship\` ADD CONSTRAINT \`FK_5b4b4623267b28750ae11a53094\` FOREIGN KEY (\`personId\`) REFERENCES \`person\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`person_starships_starship\` ADD CONSTRAINT \`FK_18aaf7b5a5268c1d99b1385adf9\` FOREIGN KEY (\`starshipId\`) REFERENCES \`starship\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`person_images_images\` ADD CONSTRAINT \`FK_4c09184fd2f6dba71e77bb8fde2\` FOREIGN KEY (\`personId\`) REFERENCES \`person\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`person_images_images\` ADD CONSTRAINT \`FK_4592909e9fff3e1deaf5f4fbf1f\` FOREIGN KEY (\`imagesId\`) REFERENCES \`images\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`person_images_images\` DROP FOREIGN KEY \`FK_4592909e9fff3e1deaf5f4fbf1f\``);
        await queryRunner.query(`ALTER TABLE \`person_images_images\` DROP FOREIGN KEY \`FK_4c09184fd2f6dba71e77bb8fde2\``);
        await queryRunner.query(`ALTER TABLE \`person_starships_starship\` DROP FOREIGN KEY \`FK_18aaf7b5a5268c1d99b1385adf9\``);
        await queryRunner.query(`ALTER TABLE \`person_starships_starship\` DROP FOREIGN KEY \`FK_5b4b4623267b28750ae11a53094\``);
        await queryRunner.query(`ALTER TABLE \`person_vehicles_vehicle\` DROP FOREIGN KEY \`FK_dcca73435d3a911aec3a8c6a8eb\``);
        await queryRunner.query(`ALTER TABLE \`person_vehicles_vehicle\` DROP FOREIGN KEY \`FK_93eb9aed40f347d6d9eb37af39c\``);
        await queryRunner.query(`ALTER TABLE \`person_species_specie\` DROP FOREIGN KEY \`FK_768ccc6a23ed03f3e4fc27cd839\``);
        await queryRunner.query(`ALTER TABLE \`person_species_specie\` DROP FOREIGN KEY \`FK_10f5e82ddc0e1f67f779f37c21e\``);
        await queryRunner.query(`ALTER TABLE \`film_images_images\` DROP FOREIGN KEY \`FK_89bc78f7ac425ace2f1ac3765f2\``);
        await queryRunner.query(`ALTER TABLE \`film_images_images\` DROP FOREIGN KEY \`FK_020d6919690a7a20524282e6c9d\``);
        await queryRunner.query(`ALTER TABLE \`film_species_specie\` DROP FOREIGN KEY \`FK_5a19d397f578506a444ad76cfac\``);
        await queryRunner.query(`ALTER TABLE \`film_species_specie\` DROP FOREIGN KEY \`FK_57e6df74dce55bd710f01c44bb8\``);
        await queryRunner.query(`ALTER TABLE \`film_vehicles_vehicle\` DROP FOREIGN KEY \`FK_8be4e7e1014359bb4715338cf20\``);
        await queryRunner.query(`ALTER TABLE \`film_vehicles_vehicle\` DROP FOREIGN KEY \`FK_af46f6d0bef8eba92546a8c5375\``);
        await queryRunner.query(`ALTER TABLE \`film_starships_starship\` DROP FOREIGN KEY \`FK_21297c5d74a841542bcb7fe063a\``);
        await queryRunner.query(`ALTER TABLE \`film_starships_starship\` DROP FOREIGN KEY \`FK_ed79253745f81534b737ce768c1\``);
        await queryRunner.query(`ALTER TABLE \`film_planets_planet\` DROP FOREIGN KEY \`FK_6821d91826ca31cc4e4588b5355\``);
        await queryRunner.query(`ALTER TABLE \`film_planets_planet\` DROP FOREIGN KEY \`FK_9e9d858b064b7d0fa02a9764e18\``);
        await queryRunner.query(`ALTER TABLE \`film_characters_person\` DROP FOREIGN KEY \`FK_76a39805866b99358326c6153a0\``);
        await queryRunner.query(`ALTER TABLE \`film_characters_person\` DROP FOREIGN KEY \`FK_7c9df9a723ecdbadcfe83626467\``);
        await queryRunner.query(`ALTER TABLE \`vehicle_images_images\` DROP FOREIGN KEY \`FK_75dfb54dd3747d2828cff22efef\``);
        await queryRunner.query(`ALTER TABLE \`vehicle_images_images\` DROP FOREIGN KEY \`FK_7a473001e3be0882cc92ff11d86\``);
        await queryRunner.query(`ALTER TABLE \`starship_images_images\` DROP FOREIGN KEY \`FK_f522274334f590ce009b5e4282e\``);
        await queryRunner.query(`ALTER TABLE \`starship_images_images\` DROP FOREIGN KEY \`FK_7aabd339010e33f15747fba209b\``);
        await queryRunner.query(`ALTER TABLE \`planet_images_images\` DROP FOREIGN KEY \`FK_2ab67e264e6edbb7427f6fea3c8\``);
        await queryRunner.query(`ALTER TABLE \`planet_images_images\` DROP FOREIGN KEY \`FK_1de22794654cb72e7538b865cd1\``);
        await queryRunner.query(`ALTER TABLE \`specie_images_images\` DROP FOREIGN KEY \`FK_2ad1e7a7930c3ccaf75d4a7f050\``);
        await queryRunner.query(`ALTER TABLE \`specie_images_images\` DROP FOREIGN KEY \`FK_42f307c19ca832703852189497a\``);
        await queryRunner.query(`ALTER TABLE \`person\` DROP FOREIGN KEY \`FK_997edaa4b7b556c0d557cc6e1bb\``);
        await queryRunner.query(`ALTER TABLE \`specie\` DROP FOREIGN KEY \`FK_55bd54b68d6b9484ec932556182\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_368e146b785b574f42ae9e53d5e\``);
        await queryRunner.query(`DROP INDEX \`IDX_4592909e9fff3e1deaf5f4fbf1\` ON \`person_images_images\``);
        await queryRunner.query(`DROP INDEX \`IDX_4c09184fd2f6dba71e77bb8fde\` ON \`person_images_images\``);
        await queryRunner.query(`DROP TABLE \`person_images_images\``);
        await queryRunner.query(`DROP INDEX \`IDX_18aaf7b5a5268c1d99b1385adf\` ON \`person_starships_starship\``);
        await queryRunner.query(`DROP INDEX \`IDX_5b4b4623267b28750ae11a5309\` ON \`person_starships_starship\``);
        await queryRunner.query(`DROP TABLE \`person_starships_starship\``);
        await queryRunner.query(`DROP INDEX \`IDX_dcca73435d3a911aec3a8c6a8e\` ON \`person_vehicles_vehicle\``);
        await queryRunner.query(`DROP INDEX \`IDX_93eb9aed40f347d6d9eb37af39\` ON \`person_vehicles_vehicle\``);
        await queryRunner.query(`DROP TABLE \`person_vehicles_vehicle\``);
        await queryRunner.query(`DROP INDEX \`IDX_768ccc6a23ed03f3e4fc27cd83\` ON \`person_species_specie\``);
        await queryRunner.query(`DROP INDEX \`IDX_10f5e82ddc0e1f67f779f37c21\` ON \`person_species_specie\``);
        await queryRunner.query(`DROP TABLE \`person_species_specie\``);
        await queryRunner.query(`DROP INDEX \`IDX_89bc78f7ac425ace2f1ac3765f\` ON \`film_images_images\``);
        await queryRunner.query(`DROP INDEX \`IDX_020d6919690a7a20524282e6c9\` ON \`film_images_images\``);
        await queryRunner.query(`DROP TABLE \`film_images_images\``);
        await queryRunner.query(`DROP INDEX \`IDX_5a19d397f578506a444ad76cfa\` ON \`film_species_specie\``);
        await queryRunner.query(`DROP INDEX \`IDX_57e6df74dce55bd710f01c44bb\` ON \`film_species_specie\``);
        await queryRunner.query(`DROP TABLE \`film_species_specie\``);
        await queryRunner.query(`DROP INDEX \`IDX_8be4e7e1014359bb4715338cf2\` ON \`film_vehicles_vehicle\``);
        await queryRunner.query(`DROP INDEX \`IDX_af46f6d0bef8eba92546a8c537\` ON \`film_vehicles_vehicle\``);
        await queryRunner.query(`DROP TABLE \`film_vehicles_vehicle\``);
        await queryRunner.query(`DROP INDEX \`IDX_21297c5d74a841542bcb7fe063\` ON \`film_starships_starship\``);
        await queryRunner.query(`DROP INDEX \`IDX_ed79253745f81534b737ce768c\` ON \`film_starships_starship\``);
        await queryRunner.query(`DROP TABLE \`film_starships_starship\``);
        await queryRunner.query(`DROP INDEX \`IDX_6821d91826ca31cc4e4588b535\` ON \`film_planets_planet\``);
        await queryRunner.query(`DROP INDEX \`IDX_9e9d858b064b7d0fa02a9764e1\` ON \`film_planets_planet\``);
        await queryRunner.query(`DROP TABLE \`film_planets_planet\``);
        await queryRunner.query(`DROP INDEX \`IDX_76a39805866b99358326c6153a\` ON \`film_characters_person\``);
        await queryRunner.query(`DROP INDEX \`IDX_7c9df9a723ecdbadcfe8362646\` ON \`film_characters_person\``);
        await queryRunner.query(`DROP TABLE \`film_characters_person\``);
        await queryRunner.query(`DROP INDEX \`IDX_75dfb54dd3747d2828cff22efe\` ON \`vehicle_images_images\``);
        await queryRunner.query(`DROP INDEX \`IDX_7a473001e3be0882cc92ff11d8\` ON \`vehicle_images_images\``);
        await queryRunner.query(`DROP TABLE \`vehicle_images_images\``);
        await queryRunner.query(`DROP INDEX \`IDX_f522274334f590ce009b5e4282\` ON \`starship_images_images\``);
        await queryRunner.query(`DROP INDEX \`IDX_7aabd339010e33f15747fba209\` ON \`starship_images_images\``);
        await queryRunner.query(`DROP TABLE \`starship_images_images\``);
        await queryRunner.query(`DROP INDEX \`IDX_2ab67e264e6edbb7427f6fea3c\` ON \`planet_images_images\``);
        await queryRunner.query(`DROP INDEX \`IDX_1de22794654cb72e7538b865cd\` ON \`planet_images_images\``);
        await queryRunner.query(`DROP TABLE \`planet_images_images\``);
        await queryRunner.query(`DROP INDEX \`IDX_2ad1e7a7930c3ccaf75d4a7f05\` ON \`specie_images_images\``);
        await queryRunner.query(`DROP INDEX \`IDX_42f307c19ca832703852189497\` ON \`specie_images_images\``);
        await queryRunner.query(`DROP TABLE \`specie_images_images\``);
        await queryRunner.query(`DROP TABLE \`person\``);
        await queryRunner.query(`DROP TABLE \`film\``);
        await queryRunner.query(`DROP TABLE \`vehicle\``);
        await queryRunner.query(`DROP TABLE \`starship\``);
        await queryRunner.query(`DROP TABLE \`planet\``);
        await queryRunner.query(`DROP TABLE \`specie\``);
        await queryRunner.query(`DROP TABLE \`images\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP TABLE \`roles\``);
    }

}
